# Generated by Django 2.2.3 on 2019-07-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='famous',
            options={'verbose_name': 'Hall da Fama', 'verbose_name_plural': 'Famoso'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Informação', 'verbose_name_plural': 'Informações'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='medal',
            options={'verbose_name': 'Medalha', 'verbose_name_plural': 'Medalhas'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Ativitade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Depoimento', 'verbose_name_plural': 'Depoimentos'},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='famous',
            name='image',
            field=models.FileField(upload_to='hall-da-fama/'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.FileField(upload_to='time/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.FileField(upload_to='parceiros/'),
        ),
    ]
